// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.97.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace MsProjectMapper
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
[Serializable]
[XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public enum ProjectCalendarWorkWeekWeekDayDayType
{
    [XmlEnumAttribute("0")]
    Item0,
    [XmlEnumAttribute("1")]
    Item1,
    [XmlEnumAttribute("2")]
    Item2,
    [XmlEnumAttribute("3")]
    Item3,
    [XmlEnumAttribute("4")]
    Item4,
    [XmlEnumAttribute("5")]
    Item5,
    [XmlEnumAttribute("6")]
    Item6,
    [XmlEnumAttribute("7")]
    Item7,
}
}
#pragma warning restore
