// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.97.0. www.xsd2code.com
//    {"TargetFramework":"NetStandard","NameSpace":"MsProjectMapper","GenerateUnusedComplexType":true,"GenerateUnusedSimpleType":true,"Properties":{"LazyLoading":true,"AutomaticProperties":true},"XmlAttribute":{"Enabled":true},"DataAnnotationsAttribute":{"StringLengthAttribute":true,"RequiredAttribute":true,"MaxLengthAttribute":true,"MinLengthAttribute":true,"RegularExpressionAttribute":true,"RangeAttribute":true,"DefautValueAttribute":true,"Enabled":true},"ClassParams":{"GenerateInSeparateFiles":true},"Serialization":{"ShouldSerialize":{},"XmlSerializerEvent":{},"XmlOutput":{},"JsonOutput":{},"Enabled":true},"Miscellaneous":{"EnableSummaryComment":true}}
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
#pragma warning restore
