// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.97.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace MsProjectMapper
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
[Serializable]
[XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public enum ProjectResourceExtendedAttributeDurationFormat
{
    [XmlEnumAttribute("3")]
    Item3,
    [XmlEnumAttribute("4")]
    Item4,
    [XmlEnumAttribute("5")]
    Item5,
    [XmlEnumAttribute("6")]
    Item6,
    [XmlEnumAttribute("7")]
    Item7,
    [XmlEnumAttribute("8")]
    Item8,
    [XmlEnumAttribute("9")]
    Item9,
    [XmlEnumAttribute("10")]
    Item10,
    [XmlEnumAttribute("11")]
    Item11,
    [XmlEnumAttribute("12")]
    Item12,
    [XmlEnumAttribute("19")]
    Item19,
    [XmlEnumAttribute("20")]
    Item20,
    [XmlEnumAttribute("21")]
    Item21,
    [XmlEnumAttribute("35")]
    Item35,
    [XmlEnumAttribute("36")]
    Item36,
    [XmlEnumAttribute("37")]
    Item37,
    [XmlEnumAttribute("38")]
    Item38,
    [XmlEnumAttribute("39")]
    Item39,
    [XmlEnumAttribute("40")]
    Item40,
    [XmlEnumAttribute("41")]
    Item41,
    [XmlEnumAttribute("42")]
    Item42,
    [XmlEnumAttribute("43")]
    Item43,
    [XmlEnumAttribute("44")]
    Item44,
    [XmlEnumAttribute("51")]
    Item51,
    [XmlEnumAttribute("52")]
    Item52,
    [XmlEnumAttribute("53")]
    Item53,
}
}
#pragma warning restore
