// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.97.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace MsProjectMapper
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;
    using System.IO;
    using System.Text;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;

    /// <summary>
    /// Exceptions are used to define an exception sub-calendar.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/project")]
    public partial class ProjectCalendarException
    {
        private ProjectCalendarExceptionTimePeriod _timePeriod;
        private ProjectCalendarExceptionWorkingTimes _workingTimes;
        private static XmlSerializer _serializer;
        /// <summary>
        /// Whether the range of recurrence is defined by entering a number of occurrences. False specifies that the range of recurrence is defined by entering a finish date.
        /// </summary>
        [Range(0, 1)]
        public int EnteredByOccurrences { get; set; }
        /// <summary>
        /// The number of occurrences for which the calendar exception is valid.
        /// </summary>
        public int Occurrences { get; set; }
        /// <summary>
        /// The name of the exception.
        /// </summary>
        [MaxLengthAttribute(512)]
        [StringLengthAttribute(512)]
        public string Name { get; set; }
        /// <summary>
        /// The exception type. Values are: 1=Daily, 2=Yearly by day of the month, 3=Yearly by position, 4=Monthly by day of the month, 5=Monthly by position, 6=Weekly, 7=By day count, 8=By weekday count, 9=No exception type.
        /// </summary>
        public ProjectCalendarExceptionType Type { get; set; }
        /// <summary>
        /// The period of recurrence for the exception.
        /// </summary>
        [DefaultValue(0)]
        public int Period { get; set; }
        /// <summary>
        /// The days of the week on which the exception is valid. Values are: 1=Sunday, 2=Monday, 4=Tuesday, 8=Wednesday, 16=Thursday, 32=Friday, 64=Saturday.
        /// </summary>
        [DefaultValue(0)]
        public int DaysOfWeek { get; set; }
        /// <summary>
        /// The month item for which an exception recurrence is scheduled. Values are: 0=Day, 1=Weekday, 2=WeekendDay, 3=Sunday, 4=Monday, 5=Tuesday, 6=Wednesday, 7=Thursday, 8=Friday, 9=Saturday.
        /// </summary>
        [DefaultValue(typeof(ProjectCalendarExceptionMonthItem), nameof(ProjectCalendarExceptionMonthItem.Item0))]
        public ProjectCalendarExceptionMonthItem MonthItem { get; set; }
        /// <summary>
        /// The position of a month item within a month. Values are: 0=First position, 1=Second position, 2=Third position, 3=Fourth position, 4=Last position.
        /// </summary>
        [DefaultValue(typeof(ProjectCalendarExceptionMonthPosition), nameof(ProjectCalendarExceptionMonthPosition.Item0))]
        public ProjectCalendarExceptionMonthPosition MonthPosition { get; set; }
        /// <summary>
        /// The month for which an exception recurrence is scheduled. Values are: 0=January, 1=February, 2=March, 3=April, 4=May, 5=June, 6=July, 7=August, 8=September, 9=October, 10=November, 11=December.
        /// </summary>
        [DefaultValue(typeof(ProjectCalendarExceptionMonth), nameof(ProjectCalendarExceptionMonth.Item0))]
        public ProjectCalendarExceptionMonth Month { get; set; }
        /// <summary>
        /// The day of the month on which an exception recurrence is scheduled.
        /// </summary>
        [DefaultValue(0)]
        public int MonthDay { get; set; }
        /// <summary>
        /// Whether the specified date or day type is working.
        /// </summary>
        [Range(0, 1)]
        public int DayWorking { get; set; }

        /// <summary>
        /// Defines a contiguous set of exception days.
        /// </summary>
        public ProjectCalendarExceptionTimePeriod TimePeriod
        {
            get
            {
                if ((_timePeriod == null))
                {
                    _timePeriod = new ProjectCalendarExceptionTimePeriod();
                }
                return _timePeriod;
            }
            set
            {
                _timePeriod = value;
            }
        }

        /// <summary>
        /// The collection of working times that define the time worked on the weekday. One of these must be present, and there can be no more than five.
        /// </summary>
        public ProjectCalendarExceptionWorkingTimes WorkingTimes
        {
            get
            {
                return _workingTimes;
            }
            set
            {
                _workingTimes = value;
            }
        }

        private static XmlSerializer SerializerXML
        {
            get
            {
                if ((_serializer == null))
                {
                    _serializer = new XmlSerializerFactory().CreateSerializer(typeof(ProjectCalendarException));
                }
                return _serializer;
            }
        }

        #region Serialize/Deserialize
        /// <summary>
        /// Serialize ProjectCalendarException object
        /// </summary>
        /// <returns>XML value</returns>
        public virtual string Serialize()
        {
            StreamReader streamReader = null;
            MemoryStream memoryStream = null;
            try
            {
                memoryStream = new MemoryStream();
                System.Xml.XmlWriterSettings xmlWriterSettings = new System.Xml.XmlWriterSettings();
                System.Xml.XmlWriter xmlWriter = XmlWriter.Create(memoryStream, xmlWriterSettings);
                SerializerXML.Serialize(xmlWriter, this);
                memoryStream.Seek(0, SeekOrigin.Begin);
                streamReader = new StreamReader(memoryStream);
                return streamReader.ReadToEnd();
            }
            finally
            {
                if ((streamReader != null))
                {
                    streamReader.Dispose();
                }
                if ((memoryStream != null))
                {
                    memoryStream.Dispose();
                }
            }
        }

        /// <summary>
        /// Deserializes ProjectCalendarException object
        /// </summary>
        /// <param name="input">string workflow markup to deserialize</param>
        /// <param name="obj">Output ProjectCalendarException object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
        public static bool Deserialize(string input, out ProjectCalendarException obj, out Exception exception)
        {
            exception = null;
            obj = default(ProjectCalendarException);
            try
            {
                obj = Deserialize(input);
                return true;
            }
            catch (Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public static bool Deserialize(string input, out ProjectCalendarException obj)
        {
            Exception exception = null;
            return Deserialize(input, out obj, out exception);
        }

        public static ProjectCalendarException Deserialize(string input)
        {
            StringReader stringReader = null;
            try
            {
                stringReader = new StringReader(input);
                return ((ProjectCalendarException)(SerializerXML.Deserialize(XmlReader.Create(stringReader))));
            }
            finally
            {
                if ((stringReader != null))
                {
                    stringReader.Dispose();
                }
            }
        }

        public static ProjectCalendarException Deserialize(Stream s)
        {
            return ((ProjectCalendarException)(SerializerXML.Deserialize(s)));
        }
        #endregion

        /// <summary>
        /// Serializes current ProjectCalendarException object into file
        /// </summary>
        /// <param name="fileName">full path of outupt xml file</param>
        /// <param name="exception">output Exception value if failed</param>
        /// <returns>true if can serialize and save into file; otherwise, false</returns>
        public virtual bool SaveToFile(string fileName, out Exception exception)
        {
            exception = null;
            try
            {
                SaveToFile(fileName);
                return true;
            }
            catch (Exception e)
            {
                exception = e;
                return false;
            }
        }

        public virtual void SaveToFile(string fileName)
        {
            StreamWriter streamWriter = null;
            try
            {
                string dataString = Serialize();
                FileInfo outputFile = new FileInfo(fileName);
                streamWriter = outputFile.CreateText();
                streamWriter.WriteLine(dataString);
                streamWriter.Close();
            }
            finally
            {
                if ((streamWriter != null))
                {
                    streamWriter.Dispose();
                }
            }
        }

        /// <summary>
        /// Deserializes xml markup from file into an ProjectCalendarException object
        /// </summary>
        /// <param name="fileName">string xml file to load and deserialize</param>
        /// <param name="obj">Output ProjectCalendarException object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
        public static bool LoadFromFile(string fileName, out ProjectCalendarException obj, out Exception exception)
        {
            exception = null;
            obj = default(ProjectCalendarException);
            try
            {
                obj = LoadFromFile(fileName);
                return true;
            }
            catch (Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public static bool LoadFromFile(string fileName, out ProjectCalendarException obj)
        {
            Exception exception = null;
            return LoadFromFile(fileName, out obj, out exception);
        }

        public static ProjectCalendarException LoadFromFile(string fileName)
        {
            FileStream file = null;
            StreamReader sr = null;
            try
            {
                file = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                sr = new StreamReader(file);
                string dataString = sr.ReadToEnd();
                sr.Close();
                file.Close();
                return Deserialize(dataString);
            }
            finally
            {
                if ((file != null))
                {
                    file.Dispose();
                }
                if ((sr != null))
                {
                    sr.Dispose();
                }
            }
        }
    }
}
#pragma warning restore
