// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.97.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace MsProjectMapper
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

/// <summary>
/// The table of entries that define the outline code mask.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public partial class ProjectWBSMasks
{
    private List<ProjectWBSMasksWBSMask> _wBSMask;
    private static XmlSerializer _serializer;
    /// <summary>
    /// Whether WBS codes are unique for new tasks.
    /// </summary>
        [DefaultValue(false)]
        public bool VerifyUniqueCodes { get; set; }
    /// <summary>
    /// Whether WBS codes are generated for new tasks.
    /// </summary>
        [DefaultValue(false)]
        public bool GenerateCodes { get; set; }
    /// <summary>
    /// The prefix for all WBS codes.
    /// </summary>
        [MaxLengthAttribute(50)]
        [StringLengthAttribute(50)]
        public string Prefix { get; set; }

    /// <summary>
    /// ProjectWBSMasks class constructor
    /// </summary>
    public ProjectWBSMasks()
    {
        VerifyUniqueCodes = false;
        GenerateCodes = false;
    }

    /// <summary>
    /// The WBS Mask that is applied to all tasks in the Project.
    /// </summary>
    [XmlElement("WBSMask")]
    public List<ProjectWBSMasksWBSMask> WBSMask
    {
        get
        {
            if ((_wBSMask == null))
            {
                _wBSMask = new List<ProjectWBSMasksWBSMask>();
            }
            return _wBSMask;
        }
        set
        {
            _wBSMask = value;
        }
    }

    private static XmlSerializer SerializerXML
    {
        get
        {
            if ((_serializer == null))
            {
                _serializer = new XmlSerializerFactory().CreateSerializer(typeof(ProjectWBSMasks));
            }
            return _serializer;
        }
    }

    #region Serialize/Deserialize
    /// <summary>
    /// Serialize ProjectWBSMasks object
    /// </summary>
    /// <returns>XML value</returns>
    public virtual string Serialize()
    {
        StreamReader streamReader = null;
        MemoryStream memoryStream = null;
        try
        {
            memoryStream = new MemoryStream();
            System.Xml.XmlWriterSettings xmlWriterSettings = new System.Xml.XmlWriterSettings();
            System.Xml.XmlWriter xmlWriter = XmlWriter.Create(memoryStream, xmlWriterSettings);
            SerializerXML.Serialize(xmlWriter, this);
            memoryStream.Seek(0, SeekOrigin.Begin);
            streamReader = new StreamReader(memoryStream);
            return streamReader.ReadToEnd();
        }
        finally
        {
            if ((streamReader != null))
            {
                streamReader.Dispose();
            }
            if ((memoryStream != null))
            {
                memoryStream.Dispose();
            }
        }
    }

    /// <summary>
    /// Deserializes ProjectWBSMasks object
    /// </summary>
    /// <param name="input">string workflow markup to deserialize</param>
    /// <param name="obj">Output ProjectWBSMasks object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool Deserialize(string input, out ProjectWBSMasks obj, out Exception exception)
    {
        exception = null;
        obj = default(ProjectWBSMasks);
        try
        {
            obj = Deserialize(input);
            return true;
        }
        catch (Exception ex)
        {
            exception = ex;
            return false;
        }
    }

    public static bool Deserialize(string input, out ProjectWBSMasks obj)
    {
        Exception exception = null;
        return Deserialize(input, out obj, out exception);
    }

    public static ProjectWBSMasks Deserialize(string input)
    {
        StringReader stringReader = null;
        try
        {
            stringReader = new StringReader(input);
            return ((ProjectWBSMasks)(SerializerXML.Deserialize(XmlReader.Create(stringReader))));
        }
        finally
        {
            if ((stringReader != null))
            {
                stringReader.Dispose();
            }
        }
    }

    public static ProjectWBSMasks Deserialize(Stream s)
    {
        return ((ProjectWBSMasks)(SerializerXML.Deserialize(s)));
    }
    #endregion

    /// <summary>
    /// Serializes current ProjectWBSMasks object into file
    /// </summary>
    /// <param name="fileName">full path of outupt xml file</param>
    /// <param name="exception">output Exception value if failed</param>
    /// <returns>true if can serialize and save into file; otherwise, false</returns>
    public virtual bool SaveToFile(string fileName, out Exception exception)
    {
        exception = null;
        try
        {
            SaveToFile(fileName);
            return true;
        }
        catch (Exception e)
        {
            exception = e;
            return false;
        }
    }

    public virtual void SaveToFile(string fileName)
    {
        StreamWriter streamWriter = null;
        try
        {
            string dataString = Serialize();
            FileInfo outputFile = new FileInfo(fileName);
            streamWriter = outputFile.CreateText();
            streamWriter.WriteLine(dataString);
            streamWriter.Close();
        }
        finally
        {
            if ((streamWriter != null))
            {
                streamWriter.Dispose();
            }
        }
    }

    /// <summary>
    /// Deserializes xml markup from file into an ProjectWBSMasks object
    /// </summary>
    /// <param name="fileName">string xml file to load and deserialize</param>
    /// <param name="obj">Output ProjectWBSMasks object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool LoadFromFile(string fileName, out ProjectWBSMasks obj, out Exception exception)
    {
        exception = null;
        obj = default(ProjectWBSMasks);
        try
        {
            obj = LoadFromFile(fileName);
            return true;
        }
        catch (Exception ex)
        {
            exception = ex;
            return false;
        }
    }

    public static bool LoadFromFile(string fileName, out ProjectWBSMasks obj)
    {
        Exception exception = null;
        return LoadFromFile(fileName, out obj, out exception);
    }

    public static ProjectWBSMasks LoadFromFile(string fileName)
    {
        FileStream file = null;
        StreamReader sr = null;
        try
        {
            file = new FileStream(fileName, FileMode.Open, FileAccess.Read);
            sr = new StreamReader(file);
            string dataString = sr.ReadToEnd();
            sr.Close();
            file.Close();
            return Deserialize(dataString);
        }
        finally
        {
            if ((file != null))
            {
                file.Dispose();
            }
            if ((sr != null))
            {
                sr.Dispose();
            }
        }
    }
}
}
#pragma warning restore
