// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.97.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace MsProjectMapper
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
[Serializable]
[XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public enum ProjectDurationFormat
{
    [XmlEnumAttribute("3")]
    Minute,
    [XmlEnumAttribute("4")]
    EMinute,
    [XmlEnumAttribute("5")]
    Hour,
    [XmlEnumAttribute("6")]
    EHour,
    [XmlEnumAttribute("7")]
    Day,
    [XmlEnumAttribute("8")]
    EDay,
    [XmlEnumAttribute("9")]
    Week,
    [XmlEnumAttribute("10")]
    EWeek,
    [XmlEnumAttribute("11")]
    Month,
    [XmlEnumAttribute("12")]
    EMonth,
    [XmlEnumAttribute("19")]
    Percent,
    [XmlEnumAttribute("20")]
    EPercent,
    [XmlEnumAttribute("21")]
    Null,
    [XmlEnumAttribute("35")]
    MinuteQuestion,
    [XmlEnumAttribute("36")]
    EMinuteQuestion,
    [XmlEnumAttribute("37")]
    HourQuestion,
    [XmlEnumAttribute("38")]
    EHourQuestion,
    [XmlEnumAttribute("39")]
    DayQuestion,
    [XmlEnumAttribute("40")]
    EDayQuestion,
    [XmlEnumAttribute("41")]
    WeekQuestion,
    [XmlEnumAttribute("42")]
    EWeekQuestion,
    [XmlEnumAttribute("43")]
    MonthQuestion,
    [XmlEnumAttribute("44")]
    EMonthQuestion,
    [XmlEnumAttribute("51")]
    PercentQuestion,
    [XmlEnumAttribute("52")]
    EPercentQuestion,
    [XmlEnumAttribute("53")]
    Null2,
}
}
#pragma warning restore
