// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.97.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace MsProjectMapper
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

/// <summary>
/// The Fiscal Year starting month. Values are: 1=January, 2=February, 3=March, 4=April, 5=May, 6=June, 7=July, 8=August, 9=September, 10=October, 11=November, 12=December.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
[Serializable]
[XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public enum ProjectFYStartDate
{
    [XmlEnumAttribute("1")]
    Item1,
    [XmlEnumAttribute("2")]
    Item2,
    [XmlEnumAttribute("3")]
    Item3,
    [XmlEnumAttribute("4")]
    Item4,
    [XmlEnumAttribute("5")]
    Item5,
    [XmlEnumAttribute("6")]
    Item6,
    [XmlEnumAttribute("7")]
    Item7,
    [XmlEnumAttribute("8")]
    Item8,
    [XmlEnumAttribute("9")]
    Item9,
    [XmlEnumAttribute("10")]
    Item10,
    [XmlEnumAttribute("11")]
    Item11,
    [XmlEnumAttribute("12")]
    Item12,
}
}
#pragma warning restore
