// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.97.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace MsProjectMapper
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
[Serializable]
[XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public enum TimephasedDataTypeType
{
    [XmlEnumAttribute("1")]
    Item1,
    [XmlEnumAttribute("2")]
    Item2,
    [XmlEnumAttribute("3")]
    Item3,
    [XmlEnumAttribute("4")]
    Item4,
    [XmlEnumAttribute("5")]
    Item5,
    [XmlEnumAttribute("6")]
    Item6,
    [XmlEnumAttribute("7")]
    Item7,
    [XmlEnumAttribute("8")]
    Item8,
    [XmlEnumAttribute("9")]
    Item9,
    [XmlEnumAttribute("10")]
    Item10,
    [XmlEnumAttribute("11")]
    Item11,
    [XmlEnumAttribute("16")]
    Item16,
    [XmlEnumAttribute("17")]
    Item17,
    [XmlEnumAttribute("18")]
    Item18,
    [XmlEnumAttribute("19")]
    Item19,
    [XmlEnumAttribute("20")]
    Item20,
    [XmlEnumAttribute("21")]
    Item21,
    [XmlEnumAttribute("22")]
    Item22,
    [XmlEnumAttribute("23")]
    Item23,
    [XmlEnumAttribute("24")]
    Item24,
    [XmlEnumAttribute("25")]
    Item25,
    [XmlEnumAttribute("26")]
    Item26,
    [XmlEnumAttribute("27")]
    Item27,
    [XmlEnumAttribute("28")]
    Item28,
    [XmlEnumAttribute("29")]
    Item29,
    [XmlEnumAttribute("30")]
    Item30,
    [XmlEnumAttribute("31")]
    Item31,
    [XmlEnumAttribute("32")]
    Item32,
    [XmlEnumAttribute("33")]
    Item33,
    [XmlEnumAttribute("34")]
    Item34,
    [XmlEnumAttribute("35")]
    Item35,
    [XmlEnumAttribute("36")]
    Item36,
    [XmlEnumAttribute("37")]
    Item37,
    [XmlEnumAttribute("38")]
    Item38,
    [XmlEnumAttribute("39")]
    Item39,
    [XmlEnumAttribute("40")]
    Item40,
    [XmlEnumAttribute("41")]
    Item41,
    [XmlEnumAttribute("42")]
    Item42,
    [XmlEnumAttribute("43")]
    Item43,
    [XmlEnumAttribute("44")]
    Item44,
    [XmlEnumAttribute("45")]
    Item45,
    [XmlEnumAttribute("46")]
    Item46,
    [XmlEnumAttribute("47")]
    Item47,
    [XmlEnumAttribute("48")]
    Item48,
    [XmlEnumAttribute("49")]
    Item49,
    [XmlEnumAttribute("50")]
    Item50,
    [XmlEnumAttribute("51")]
    Item51,
    [XmlEnumAttribute("52")]
    Item52,
    [XmlEnumAttribute("53")]
    Item53,
    [XmlEnumAttribute("54")]
    Item54,
    [XmlEnumAttribute("55")]
    Item55,
    [XmlEnumAttribute("56")]
    Item56,
    [XmlEnumAttribute("57")]
    Item57,
    [XmlEnumAttribute("58")]
    Item58,
    [XmlEnumAttribute("59")]
    Item59,
    [XmlEnumAttribute("60")]
    Item60,
    [XmlEnumAttribute("61")]
    Item61,
    [XmlEnumAttribute("62")]
    Item62,
    [XmlEnumAttribute("63")]
    Item63,
    [XmlEnumAttribute("64")]
    Item64,
    [XmlEnumAttribute("65")]
    Item65,
    [XmlEnumAttribute("66")]
    Item66,
    [XmlEnumAttribute("67")]
    Item67,
    [XmlEnumAttribute("68")]
    Item68,
    [XmlEnumAttribute("69")]
    Item69,
    [XmlEnumAttribute("70")]
    Item70,
    [XmlEnumAttribute("71")]
    Item71,
    [XmlEnumAttribute("72")]
    Item72,
    [XmlEnumAttribute("73")]
    Item73,
    [XmlEnumAttribute("74")]
    Item74,
    [XmlEnumAttribute("75")]
    Item75,
    [XmlEnumAttribute("76")]
    Item76,
}
}
#pragma warning restore
