// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace EFCoreProjectionTest.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCoreProjectionTest.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ac3c4f6-bc48-4c46-9cf3-941278f8750f"),
                            Name = "Area1"
                        },
                        new
                        {
                            Id = new Guid("01b3bc52-a95c-4f68-aff0-75c19e0059c0"),
                            Name = "Area2"
                        },
                        new
                        {
                            Id = new Guid("a9618afd-daa7-48fb-99e3-1d632a72778a"),
                            Name = "Area3"
                        });
                });

            modelBuilder.Entity("EFCoreProjectionTest.Subarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AreaId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Subareas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3d57630-8cc2-4c56-b472-ac48c3e7f0d7"),
                            AreaId = new Guid("2ac3c4f6-bc48-4c46-9cf3-941278f8750f"),
                            Name = "Subarea1"
                        },
                        new
                        {
                            Id = new Guid("f4c63692-acea-4978-a270-f560878f5a58"),
                            AreaId = new Guid("2ac3c4f6-bc48-4c46-9cf3-941278f8750f"),
                            Name = "Subarea2"
                        },
                        new
                        {
                            Id = new Guid("78bc9112-4aa3-418f-9181-4fc4628c7630"),
                            AreaId = new Guid("2ac3c4f6-bc48-4c46-9cf3-941278f8750f"),
                            Name = "Subarea3"
                        },
                        new
                        {
                            Id = new Guid("2da08f02-e6ee-436e-9776-4d48a73e6c21"),
                            AreaId = new Guid("01b3bc52-a95c-4f68-aff0-75c19e0059c0"),
                            Name = "Subarea4"
                        },
                        new
                        {
                            Id = new Guid("4616a938-2add-4a51-9aca-6bbd3c9dd815"),
                            AreaId = new Guid("01b3bc52-a95c-4f68-aff0-75c19e0059c0"),
                            Name = "Subarea5"
                        },
                        new
                        {
                            Id = new Guid("980b5807-b519-4038-9a04-8a0a96b60be2"),
                            AreaId = new Guid("01b3bc52-a95c-4f68-aff0-75c19e0059c0"),
                            Name = "Subarea6"
                        },
                        new
                        {
                            Id = new Guid("8d07713f-2033-4bcf-959e-e8cbfaacd63e"),
                            AreaId = new Guid("01b3bc52-a95c-4f68-aff0-75c19e0059c0"),
                            Name = "Subarea7"
                        },
                        new
                        {
                            Id = new Guid("0ce400d2-3dff-41d4-8241-7461b7f81905"),
                            AreaId = new Guid("a9618afd-daa7-48fb-99e3-1d632a72778a"),
                            Name = "Subarea8"
                        },
                        new
                        {
                            Id = new Guid("585eecc6-c3b0-416a-a8a5-6a9240b2debe"),
                            AreaId = new Guid("a9618afd-daa7-48fb-99e3-1d632a72778a"),
                            Name = "Subarea9"
                        });
                });

            modelBuilder.Entity("EFCoreProjectionTest.Subarea", b =>
                {
                    b.HasOne("EFCoreProjectionTest.Area")
                        .WithMany("Subareas")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
